// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOKdl-I46j1mcx-p963XgR-muK8qDx7mc',
    appId: '1:935933039172:web:022731a72a48132f8fe211',
    messagingSenderId: '935933039172',
    projectId: 'pawvera-3578f',
    authDomain: 'pawvera-3578f.firebaseapp.com',
    storageBucket: 'pawvera-3578f.firebasestorage.app',
    measurementId: 'G-PV6PKW2DGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3qD4cGRf2sAlie_ojW9KzIeL3KAHt-3s',
    appId: '1:935933039172:android:e1c2d7f97f44a2858fe211',
    messagingSenderId: '935933039172',
    projectId: 'pawvera-3578f',
    storageBucket: 'pawvera-3578f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn19F8sJK8zcYxhdniJaBxI08qk9RFhjw',
    appId: '1:935933039172:ios:d9f8db75f5b5ea028fe211',
    messagingSenderId: '935933039172',
    projectId: 'pawvera-3578f',
    storageBucket: 'pawvera-3578f.firebasestorage.app',
    iosBundleId: 'com.example.pawvera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn19F8sJK8zcYxhdniJaBxI08qk9RFhjw',
    appId: '1:935933039172:ios:d9f8db75f5b5ea028fe211',
    messagingSenderId: '935933039172',
    projectId: 'pawvera-3578f',
    storageBucket: 'pawvera-3578f.firebasestorage.app',
    iosBundleId: 'com.example.pawvera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOKdl-I46j1mcx-p963XgR-muK8qDx7mc',
    appId: '1:935933039172:web:80753060f06b6b6c8fe211',
    messagingSenderId: '935933039172',
    projectId: 'pawvera-3578f',
    authDomain: 'pawvera-3578f.firebaseapp.com',
    storageBucket: 'pawvera-3578f.firebasestorage.app',
    measurementId: 'G-09EJP75TBX',
  );
}
